### ISSUE TITLE
Migration to Node 16

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1376]
**Todo:** 

- [x] Migrate from node-webcrypto-ossl to the new native [Web Crypto API ](https://nodejs.org/api/webcrypto.html)
- [x] Remove Open-Zwave integration backend side
- [x] Frontend side, add a way to migrate Open-Zwave devices to a MQTT device

**Comment by atrovato** [comment]
Work in progress, blocked by zwavejs migration.
